# 测试频率显示配置 - xaxis_frequency = false
[global]
log_level = "INFO"
description = "测试频率转换功能"
version = "2.0"

[paths]
input_npz_dir = "./output/npz/"
inventory_path = "./input/BJ.XML"
output_dir = "./output/plots_test/"

[plotting]
plot_type = ["standard"]
npz_merge_strategy = "auto"
# 图像参数已硬编码：dpi=300, figure_size自动适应

[standard]
show_histogram = true
show_percentiles = true
show_noise_models = true
show_mode = true
show_mean = true
standard_grid = true
period_lim = [0.02, 50.0]
xaxis_frequency = false  # 显示周期（秒），不是频率
cumulative_plot = false
coverage_alpha = 0.5
standard_cmap = "hot_r_custom"

[standard.percentiles]
values = [10, 50, 90]
color = "blue"
linewidth = 2.0
linestyle = "--"
alpha = 0.8

[standard.peterson]
nlnm_color = "red"
nhnm_color = "orange"
linewidth = 2.0
linestyle = "--"
alpha = 1.0

[standard.mode]
color = "green"
linewidth = 2.0
linestyle = "-"
alpha = 0.9

[standard.mean]
color = "purple"
linewidth = 2.0
linestyle = "-"
alpha = 0.9

[colors]
available_cmaps = ["hot_r_custom"]

[advanced]
matplotlib_backend = "Agg"
enable_chinese_fonts = true
memory_optimization = true 