# PPSD 单文件处理配置文件
# 使用方法：python run_cp_ppsd.py input/config_single_file.toml
# 此配置文件将为每个MiniSEED文件生成一个独立的NPZ文件
# 后续可以使用ObsPy的PPSD.add_npz()方法进行合并

# === 1. 全局操作控制 ===
log_level = "DEBUG" # 日志级别："DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"

# === 2. 输入数据与输出路径 ===
# mseed_pattern 可以是glob模式 (如 "./data/*.mseed") 或一个目录路径 (如 "./data/")。
# 如果是目录路径，脚本将递归搜索该目录下的所有miniseed文件
mseed_pattern = "./data/"                # 地震数据文件目录或glob模式
inventory_path = "./input/BJ.dataless"   # 仪器响应文件路径
output_dir = "./output/npz_single"       # NPZ文件输出目录（单文件模式）

# === 3. 输出生成控制 ===
# 单文件模式下，文件名会自动包含原始MiniSEED文件名信息
# output_npz_filename_pattern 可以进一步自定义命名规则
# 时间信息来自MiniSEED数据的开始时间:
#     {year}, {month}, {day}, {hour}, {minute}, {second}, {julday}
#     {datetime} (例如 YYYYMMDDHHMM 格式的紧凑时间戳)
# 台站信息: {network}, {station}, {location}, {channel}
# 注意：在单文件模式下，原始文件名会自动添加到生成的文件名前缀中
output_npz_filename_pattern = "PPSD_{datetime}_{network}-{station}-{location}-{channel}.npz"

# === 4. PPSD核心计算参数 ([args]表内) ===
[args]
# --- 时间分段与窗口 ---
ppsd_length = 3600                    # 时间窗口长度（秒），标准1小时
overlap = 0.5                         # 窗口重叠比例，50%重叠

# --- 频率/周期域参数 ---
period_limits = [0.01, 1000.0]        # PPSD计算的周期范围（秒）
period_smoothing_width_octaves = 1.0  # 周期平滑宽度（倍频程）
period_step_octaves = 0.125           # 周期步长（1/8倍频程）

# --- 振幅域参数 (功率分箱) ---
db_bins = [-200.0, -50.0, 0.25]       # dB分箱：[最小值, 最大值, 步长]

# --- 数据质量与选择 ---
# 间隙处理设置（基于ObsPy Stream.merge()方法）
skip_on_gaps = false                  # PPSD级别的间隙处理
                                      # false: 允许处理包含间隙的数据段（使用masked array）
                                      # true: 跳过包含间隙的时间窗口

# Stream.merge()方法参数 - 控制如何合并同一通道的多个trace段
merge_method = 0                      # 合并方法：0=标准, 1=插值, -1=清理
                                      # 0: 标准合并，重叠部分取平均值
                                      # 1: 使用插值处理重叠
                                      # -1: 仅清理，不处理重叠

# merge_fill_value = 0                # 间隙填充值，默认None使用masked array
                                      # None: 使用numpy.ma.masked_array保留间隙信息
                                      # 数值: 用指定值填充间隙
                                      # "latest": 使用间隙前的最后一个值
                                      # "interpolate": 线性插值填充

# special_handling = "None"           # 特殊仪器处理。可选值: "ringlaser", "hydrophone", "None"(默认)
                                      # None(默认): 标准地震仪处理
                                      # "ringlaser": 不进行仪器校正，仅除以sensitivity
                                      # "hydrophone": 仪器校正后不做微分操作

# === 5. 单文件模式说明 ===
# 
# 优势：
# - 每个MiniSEED文件生成独立的NPZ文件
# - 可以灵活选择要合并的时间段
# - 支持分批处理大量数据
# - 便于并行处理和错误恢复
# 
# 文件命名示例：
# 输入文件: BJ.BBS.00.BHZ.20250324000000.mseed
# 输出文件: BJ.BBS.00.BHZ.20250324000000_PPSD_202503231600_BJ-BBS-00-BHZ.npz
# 
# 后续合并使用：
# ```python
# from obspy.signal import PPSD
# 
# # 创建基础PPSD对象
# ppsd = PPSD.load_npz('第一个文件.npz')
# 
# # 添加其他文件
# ppsd.add_npz('第二个文件.npz')
# ppsd.add_npz('第三个文件.npz')
# 
# # 绘图或分析
# ppsd.plot()
# ``` 