# PPSD 绘图配置文件 - 时间范围文件名示例
# 使用方法：python run_cp_ppsd.py config_plot_time_range_example.toml
# 此配置文件演示如何使用开始时间和结束时间变量来生成包含时间范围的文件名

# ========================================
# 1. 全局设置
# ========================================
[global]
log_level = "INFO"
description = "PPSD绘图配置文件 - 时间范围文件名示例"
version = "2.0"

# ========================================
# 2. 输入输出配置
# ========================================
[paths]
input_npz_dir = "./output/npz/"
inventory_path = "./input/BJ.XML"
output_dir = "./output/plots/"

# 使用时间范围的文件名模式示例
# 这将生成类似这样的文件名：
# standard_202503231600_202503261600_BJ-DSQ-00-SHZ.png
# temporal_202503231600_202503261600_BJ-DAX-00-BHZ.png
# spectrogram_202503231600_202503261600_BJ-FHY-00-BHZ.png
output_filename_pattern = "{plot_type}_{start_datetime}_{end_datetime}_{network}-{station}-{location}-{channel}.png"

# 其他时间格式示例（可选择使用）：
# 详细时间范围: "{plot_type}_{start_year}{start_month:02d}{start_day:02d}_{start_hour:02d}{start_minute:02d}_to_{end_year}{end_month:02d}{end_day:02d}_{end_hour:02d}{end_minute:02d}_{network}-{station}-{location}-{channel}.png"
# 日期范围: "{plot_type}_{start_year}-{start_month:02d}-{start_day:02d}_to_{end_year}-{end_month:02d}-{end_day:02d}_{network}.{station}.{location}.{channel}.png"
# 仅日期: "{plot_type}_{start_year}{start_month:02d}{start_day:02d}_{end_year}{end_month:02d}{end_day:02d}_{network}_{station}_{channel}.png"

# ========================================
# 3. 绘图基本设置
# ========================================
[plotting]
plot_types = ["standard", "temporal", "spectrogram"]
npz_merge_strategy = "auto"  # 合并策略，显示时间范围
# 图像参数已硬编码：dpi=300, figure_size自动适应

# ========================================
# 4. 标准图配置
# ========================================
[standard]
show_histogram = true
show_percentiles = true
show_noise_models = true
show_coverage = true
show_mode = true
show_mean = false

standard_grid = true
period_lim = [0.01, 50.0]
xaxis_frequency = false
cumulative_plot = false
coverage_alpha = 0.5
standard_cmap = "hot_r_custom"

# --- 百分位数线配置 ---
[standard.percentiles]
values = [10, 50, 90]
color = "lightgray"
linewidth = 1.0
linestyle = "--"
alpha = 0.8

# --- 皮特森曲线配置 ---
[standard.peterson]
nlnm_color = "lightgray"
nhnm_color = "lightgray"
linewidth = 1.0
linestyle = "--"
alpha = 1.0

# --- 众数线配置 ---
[standard.mode]
color = "orange"
linewidth = 1.0
linestyle = "-"
alpha = 0.9

# ========================================
# 5. 时间演化图配置
# ========================================
[temporal]
plot_periods = [0.1, 1.0, 8.0, 20.0]
time_format_x = "%H:%M"
grid = true
cmap = "Blues"

# ========================================
# 6. 频谱图配置
# ========================================
[spectrogram]
clim = [-180, -100]
time_format_x = "%Y-%m-%d"
grid = true
cmap = "ocean_r_custom"

# ========================================
# 7. 颜色配置
# ========================================
[colors]
available_cmaps = [
    "viridis_custom",
    "ocean_custom", 
    "ocean_r_custom",
    "hot_r_custom",
    "plasma_custom",
    "CMRmap_r_custom"
]

[colors.presets]
primary = "blue"
secondary = "red"
accent = "orange"
neutral = "lightgray"

# ========================================
# 8. 高级设置
# ========================================
[advanced]
matplotlib_backend = "Agg"
font_family = "WenQuanYi Micro Hei"
enable_chinese_fonts = true
memory_optimization = true
parallel_processing = false

[advanced.compatibility]
obspy_version = ">=1.4.0"
numpy_version = ">=1.20.0"
matplotlib_version = ">=3.5.0" 