# PPSD NPZ文件合并绘图配置文件
# 使用方法：python run_cp_ppsd.py input/config_plot_npz_merge.toml
# 此配置文件使用ObsPy的add_npz()方法正确合并单文件模式生成的NPZ文件

# === 1. 全局操作控制 ===
log_level = "INFO"  # 日志级别："DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"

# === 2. 输入数据与输出路径 ===
input_npz_dir = "./output/npz"    # 单文件模式生成的NPZ文件目录
inventory_path = "./input/BJ.dataless"   # 仪器响应文件路径（可选，用于绘图时的元数据）
output_dir = "./output/plots_merged"     # 合并图像输出目录

# === 3. 输出文件命名 ===
# 合并模式下的文件命名模式
# {plot_type} 会被替换为实际的绘图类型 (standard, temporal, spectrogram)
# 时间信息来自合并后的时间范围:
#     {datetime} 会被自动替换为 merged_starttime-endtime 格式
# 台站信息: {network}, {station}, {location}, {channel}
output_filename_pattern = "{plot_type}_{datetime}_{network}.{station}.{location}.{channel}.png"

# === 4. 绘图参数配置 ([args]表内) ===
[args]
# --- 绘图类型选择 ---
plot_type = ["standard", "temporal"]     # 可选: "standard", "temporal", "spectrogram"
                                          # 可以是单个字符串或列表

# --- NPZ合并策略 ---
npz_merge_strategy = "auto"               # 合并策略: "auto", "none"
                                          # "auto": 自动按SEED ID分组并使用add_npz()合并
                                          # "none": 每个NPZ文件单独绘图

# === 5. 标准PPSD图参数 ===
# --- 基本显示设置 ---
period_lim = [0.01, 1000.0]              # 周期显示范围（秒）
show_coverage = true                      # 显示数据覆盖度
coverage_alpha = 0.3                     # 覆盖度透明度 (0.0-1.0)

# --- 配色方案 ---
standard_cmap = "viridis"                 # 标准图配色方案

# --- 噪声模型显示 ---
show_noise_models = true                  # 显示Peterson噪声模型 (NLNM/NHNM)

# --- 统计线显示 ---
show_percentiles = true                   # 显示百分位数线
percentiles = [10, 50, 90]               # 要显示的百分位数
show_mode = false                         # 显示众数线
show_mean = false                         # 显示均值线

# --- 坐标轴设置 ---
xaxis_frequency = false                   # X轴是否显示频率 (false=周期, true=频率)

# === 6. 时间演化图参数 ===
temporal_plot_periods = [1.0, 8.0, 20.0]  # 时间演化图显示的周期 (秒)

# === 7. 频谱图参数 ===
spectrogram_cmap = "plasma"               # 频谱图配色方案
# clim = [-180, -120]                     # 颜色刻度范围 (可选)

# === 8. 合并模式说明 ===
#
# 自动合并模式 (npz_merge_strategy = "auto"):
# - 程序会自动按SEED ID (network.station.location.channel) 分组NPZ文件
# - 使用ObsPy的PPSD.add_npz()方法正确合并同一台站通道的多个时间段
# - ObsPy会自动处理重复时间段、参数一致性检查等
# - 生成的图像文件名包含"merged"标识和时间范围
#
# 单独模式 (npz_merge_strategy = "none"):
# - 每个NPZ文件单独生成图像
# - 适用于需要查看每个时间段单独特征的情况
#
# 使用示例:
# 1. 先运行单文件计算: python run_cp_ppsd.py input/config_single_file.toml
# 2. 再运行合并绘图: python run_cp_ppsd.py input/config_plot_npz_merge.toml
#
# 这样可以最大化利用ObsPy的NPZ合并功能，避免手动合并可能出现的问题 